export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  featureDatabaseUrl: process.env.FEATURE_DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  openaiApiUrl: process.env.BUILT_IN_OPENAI_API_URL ?? "",
  openaiApiKey: process.env.BUILT_IN_OPENAI_API_KEY ?? "",
  openaiModel: process.env.BUILT_IN_OPENAI_MODEL ?? "gpt-5.5",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  webSearchApiId: process.env.BUILT_IN_WEB_SEARCH_API_ID ?? "",
  newsSearchApiId: process.env.BUILT_IN_NEWS_SEARCH_API_ID ?? "",
  coinMarketCapApiKey: process.env.CMC_API_KEY ?? "",
  freeChatAgentApiUrl: process.env.FREE_CHAT_AGENT_API_URL ?? "",
  freeChatAgentApiKey: process.env.FREE_CHAT_AGENT_API_KEY ?? "",
  freeChatAgentModel: process.env.FREE_CHAT_AGENT_MODEL ?? "cryptoaiiask",
};
