import "dotenv/config";
import { drizzle } from "drizzle-orm/mysql2";
import { signalTemplates } from "../drizzle/schema";

const featureDatabaseUrl = process.env.FEATURE_DATABASE_URL;
if (!featureDatabaseUrl) {
  throw new Error("FEATURE_DATABASE_URL is required to seed signal templates");
}

const db = drizzle(featureDatabaseUrl);

const templates: Array<typeof signalTemplates.$inferInsert> = [
  {
    id: "price_change_24h_gt_10pct",
    signalType: "price_change_24h_gt_10pct",
    name: "24h 价格异动",
    category: "price",
    description: "24 小时价格涨幅超过默认阈值。",
    direction: "up",
    defaultWindow: "24h",
    defaultThresholdText: "> 10%",
    severityRule: "medium: >10%; high: >20%",
    source: "token_profile",
    isEnabled: true,
    priority: 10,
  },
  {
    id: "price_streak_up_3d",
    signalType: "price_streak_up_3d",
    name: "连续 3 天上涨",
    category: "price",
    description: "连续 3 个日级周期上涨。",
    direction: "up",
    defaultWindow: "3d",
    defaultThresholdText: "3 consecutive up days",
    severityRule: "medium: 3 days; high: 4+ days",
    source: "ohlcv",
    isEnabled: true,
    priority: 11,
  },
  {
    id: "price_streak_down_3d",
    signalType: "price_streak_down_3d",
    name: "连续 3 天下跌",
    category: "price",
    description: "连续 3 个日级周期下跌。",
    direction: "down",
    defaultWindow: "3d",
    defaultThresholdText: "3 consecutive down days",
    severityRule: "medium: 3 days; high: 4+ days",
    source: "ohlcv",
    isEnabled: true,
    priority: 12,
  },
  {
    id: "volume_24h_vs_7d_avg_gt_2x",
    signalType: "volume_24h_vs_7d_avg_gt_2x",
    name: "24h 成交量放大",
    category: "volume",
    description: "24h 成交量相对近 7 天均量显著放大。",
    direction: "up",
    defaultWindow: "24h",
    defaultThresholdText: "> 7d avg 2x",
    severityRule: "medium: >2x; high: >3x",
    source: "ohlcv",
    isEnabled: true,
    priority: 20,
  },
  {
    id: "oi_change_12h_gt_50pct",
    signalType: "oi_change_12h_gt_50pct",
    name: "12h OI 异动",
    category: "oi_funding",
    description: "12 小时 OI 增长超过默认阈值。",
    direction: "up",
    defaultWindow: "12h",
    defaultThresholdText: "> 50%",
    severityRule: "medium: >50%; high: >80%",
    source: "funding_series",
    isEnabled: true,
    priority: 30,
  },
  {
    id: "oi_change_24h_gt_100pct",
    signalType: "oi_change_24h_gt_100pct",
    name: "24h OI 爆量",
    category: "oi_funding",
    description: "24 小时 OI 增长超过默认阈值。",
    direction: "up",
    defaultWindow: "24h",
    defaultThresholdText: "> 100%",
    severityRule: "medium: >100%; high: >150%",
    source: "funding_series",
    isEnabled: true,
    priority: 31,
  },
  {
    id: "funding_rate_gt_pos_threshold",
    signalType: "funding_rate_gt_pos_threshold",
    name: "资金费率偏高",
    category: "oi_funding",
    description: "当前资金费率高于正阈值。",
    direction: "up",
    defaultWindow: "now",
    defaultThresholdText: "> 0.05",
    severityRule: "medium: >0.05; high: >0.08",
    source: "funding_series",
    isEnabled: true,
    priority: 32,
  },
  {
    id: "funding_rate_lt_neg_threshold",
    signalType: "funding_rate_lt_neg_threshold",
    name: "资金费率偏低",
    category: "oi_funding",
    description: "当前资金费率低于负阈值。",
    direction: "down",
    defaultWindow: "now",
    defaultThresholdText: "< -0.05",
    severityRule: "medium: <-0.05; high: <-0.08",
    source: "funding_series",
    isEnabled: true,
    priority: 33,
  },
  {
    id: "bid_ask_ratio_gt_1_5",
    signalType: "bid_ask_ratio_gt_1_5",
    name: "盘口买卖比失衡",
    category: "depth",
    description: "买卖盘比值高于默认阈值。",
    direction: "up",
    defaultWindow: "now",
    defaultThresholdText: "> 1.5",
    severityRule: "medium: >1.5; high: >2.0",
    source: "depth_view",
    isEnabled: true,
    priority: 40,
  },
  {
    id: "buy_depth_24h_gt_50pct",
    signalType: "buy_depth_24h_gt_50pct",
    name: "24h 买盘深度增强",
    category: "depth",
    description: "24 小时买盘深度增长超过默认阈值。",
    direction: "up",
    defaultWindow: "24h",
    defaultThresholdText: "> 50%",
    severityRule: "medium: >50%; high: >80%",
    source: "depth_trend",
    isEnabled: true,
    priority: 41,
  },
  {
    id: "sell_depth_24h_drop_30pct",
    signalType: "sell_depth_24h_drop_30pct",
    name: "24h 卖盘深度下降",
    category: "depth",
    description: "24 小时卖盘深度下降超过默认阈值。",
    direction: "down",
    defaultWindow: "24h",
    defaultThresholdText: "< -30%",
    severityRule: "medium: <-30%; high: <-50%",
    source: "depth_trend",
    isEnabled: true,
    priority: 42,
  },
  {
    id: "unlock_within_7d",
    signalType: "unlock_within_7d",
    name: "7d 内解锁事件",
    category: "event",
    description: "未来 7 天内存在解锁事件。",
    direction: "upcoming",
    defaultWindow: "7d",
    defaultThresholdText: "<= 7d",
    severityRule: "higher severity when nearer to unlock date",
    source: "unlock_view",
    isEnabled: true,
    priority: 50,
  },
  {
    id: "unlock_pct_gt_2pct",
    signalType: "unlock_pct_gt_2pct",
    name: "大额解锁占比",
    category: "event",
    description: "单期解锁占总供应量比例超过默认阈值。",
    direction: "upcoming",
    defaultWindow: "event",
    defaultThresholdText: "> 2% total supply",
    severityRule: "medium: >2%; high: >5%",
    source: "unlock_view",
    isEnabled: true,
    priority: 51,
  },
  {
    id: "new_listing_detected",
    signalType: "new_listing_detected",
    name: "新上线事件",
    category: "event",
    description: "检测到新的交易所上线事件。",
    direction: "event",
    defaultWindow: "event",
    defaultThresholdText: "new listing detected",
    severityRule: "severity may depend on venue tier",
    source: "listing_view",
    isEnabled: true,
    priority: 52,
  },
  {
    id: "new_activity_detected",
    signalType: "new_activity_detected",
    name: "新活动事件",
    category: "event",
    description: "检测到新的交易所活动。",
    direction: "event",
    defaultWindow: "event",
    defaultThresholdText: "new activity detected",
    severityRule: "severity may depend on reward size",
    source: "listing_view",
    isEnabled: true,
    priority: 53,
  },
  {
    id: "top_holder_balance_change_gt_x",
    signalType: "top_holder_balance_change_gt_x",
    name: "Top Holder 持仓异动",
    category: "onchain",
    description: "前排 holder 持仓变化超过默认阈值。",
    direction: "both",
    defaultWindow: "24h",
    defaultThresholdText: "> 10%",
    severityRule: "medium: >10%; high: >20%",
    source: "onchain_holders",
    isEnabled: true,
    priority: 60,
  },
  {
    id: "new_top_holder_entered",
    signalType: "new_top_holder_entered",
    name: "新地址进入前排",
    category: "onchain",
    description: "新的地址进入前排 holder 队列。",
    direction: "in",
    defaultWindow: "snapshot",
    defaultThresholdText: "entered top holders",
    severityRule: "higher severity when entering top 10",
    source: "onchain_holders",
    isEnabled: true,
    priority: 61,
  },
  {
    id: "top_holder_exited",
    signalType: "top_holder_exited",
    name: "地址退出前排",
    category: "onchain",
    description: "地址退出前排 holder 队列。",
    direction: "out",
    defaultWindow: "snapshot",
    defaultThresholdText: "exited top holders",
    severityRule: "higher severity when exiting top 10",
    source: "onchain_holders",
    isEnabled: true,
    priority: 62,
  },
];

async function seedSignalTemplates() {
  console.log("🌱 Seeding signal templates...");

  for (const template of templates) {
    await db.insert(signalTemplates).values(template).onDuplicateKeyUpdate({
      set: {
        name: template.name,
        category: template.category,
        description: template.description ?? null,
        direction: template.direction,
        defaultWindow: template.defaultWindow ?? null,
        defaultThresholdText: template.defaultThresholdText ?? null,
        severityRule: template.severityRule ?? null,
        source: template.source,
        isEnabled: template.isEnabled ?? true,
        priority: template.priority ?? 0,
      },
    });
  }

  console.log(`✅ Seeded ${templates.length} signal templates`);
}

seedSignalTemplates()
  .catch(error => {
    console.error("❌ Failed to seed signal templates", error);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });
