import type {
  AnalysisWorkspaceViewModel,
  DashboardViewModel,
  FreeChatWorkspaceViewModel,
  MarketWorkspaceViewModel,
} from "./types";

const alphaTokens = [
  {
    symbol: "GENIUS",
    name: "Genius",
    chain: "BSC",
    alphaId: "ALPHA_887",
    listingTime: "2026-04-13 23:30 CST",
    price: 0.4960119877,
    change24h: 561.73,
    volume24h: 76427894.24,
    marketCap: 166351041.66,
    fdv: 496011987.7,
    holders: 14254,
    tags: ["New", "Momentum", "Airdrop"],
  },
  {
    symbol: "CRMon",
    name: "Salesforce (Ondo)",
    chain: "BSC",
    alphaId: "ALPHA_886",
    listingTime: "2026-04-13 18:20 CST",
    price: 173.44474288,
    change24h: 5.14,
    volume24h: 50415.53,
    marketCap: 864727.91,
    fdv: 864727.91,
    holders: null,
    tags: ["RWA", "Ondo"],
  },
  {
    symbol: "COSTon",
    name: "Costco (Ondo)",
    chain: "BSC",
    alphaId: "ALPHA_885",
    listingTime: "2026-04-13 18:20 CST",
    price: 983.47906724,
    change24h: -1.94,
    volume24h: 995.93,
    marketCap: 1256345.11,
    fdv: 1256345.11,
    holders: null,
    tags: ["RWA", "Ondo"],
  },
  {
    symbol: "BILIon",
    name: "Bilibili (Ondo)",
    chain: "BSC",
    alphaId: "ALPHA_883",
    listingTime: "2026-04-13 18:20 CST",
    price: 24.103472,
    change24h: 2.01,
    volume24h: 15224.71,
    marketCap: 303203.5,
    fdv: 303203.5,
    holders: null,
    tags: ["RWA", "China ADR"],
  },
  {
    symbol: "BIDUon",
    name: "Baidu (Ondo)",
    chain: "BSC",
    alphaId: "ALPHA_882",
    listingTime: "2026-04-13 18:20 CST",
    price: 113.665,
    change24h: 4.27,
    volume24h: 2306.6,
    marketCap: 1378624.7,
    fdv: 1378624.7,
    holders: null,
    tags: ["RWA", "Ondo"],
  },
  {
    symbol: "APPon",
    name: "AppLovin (Ondo)",
    chain: "BSC",
    alphaId: "ALPHA_880",
    listingTime: "2026-04-13 18:20 CST",
    price: 419.632376,
    change24h: 9.2,
    volume24h: 8979.52,
    marketCap: 221472.54,
    fdv: 221472.54,
    holders: null,
    tags: ["RWA", "Growth"],
  },
];

export const dashboardMockData: DashboardViewModel = {
  headline: {
    title: "Signal Board",
    summary:
      "围绕解锁、深度、OI、公告和链上事件构建统一面板，先用结构化 mock 数据占位，后续可直接替换为 REST/WebSocket 实时源。",
    refreshedAt: "2026-04-14 11:20 CST",
  },
  health: {
    dataPipeline: "5 / 7 collectors mocked",
    collectorCoverage: "P0 ready for UI integration",
    aiService: "Template router prepared",
    queueLag: "< 2m simulated",
  },
  activeSignals: [
    {
      id: "sig_20260414_001",
      symbol: "GENIUS",
      name: "Genius",
      price: 0.496,
      marketCap: 166351042,
      signalType: "alpha_momentum",
      strength: 0.91,
      urgency: "high",
      summary: "Binance Alpha 上线后 24h 量能极端放大，涨幅超过 500%，适合作为高波动观察样本，而不是直接追涨结论。",
      triggeredAt: "11:20",
      exchangeFocus: ["Binance Alpha", "Alpha feed"],
      triggeredRules: [
        { rule: "price_change_24h > 100%", value: "+561.7%", weight: 1, source: "ohlcv" },
        { rule: "volume_24h > $50M", value: "$76.4M", weight: 0.8, source: "ohlcv" },
        { rule: "holders_growth strong", value: "14.2k holders", weight: 0.5, source: "onchain" },
      ],
    },
    {
      id: "sig_20260414_002",
      symbol: "CRMon",
      name: "Salesforce (Ondo)",
      price: 173.44,
      marketCap: 864728,
      signalType: "rwa_rotation",
      strength: 0.7,
      urgency: "medium",
      summary: "RWA 主题在 Binance Alpha 新批次里集中出现，适合作为同主题篮子对比，而不是逐个单币孤立看。",
      triggeredAt: "10:48",
      exchangeFocus: ["Binance Alpha", "Ondo basket"],
      triggeredRules: [
        { rule: "theme_cluster_detected", value: "6 related tokens", weight: 0.9, source: "announcement" },
        { rule: "positive_price_change", value: "+5.1%", weight: 0.6, source: "ohlcv" },
      ],
    },
    {
      id: "sig_20260414_003",
      symbol: "APPon",
      name: "AppLovin (Ondo)",
      price: 419.63,
      marketCap: 221473,
      signalType: "relative_strength",
      strength: 0.64,
      urgency: "medium",
      summary: "同批次 RWA 标的里涨幅居前，但成交量不大，更适合放进关注名单做跟踪而不是优先交易。",
      triggeredAt: "10:15",
      exchangeFocus: ["Binance Alpha"],
      triggeredRules: [
        { rule: "top_group_change_24h", value: "+9.2%", weight: 0.7, source: "ohlcv" },
        { rule: "theme_followup", value: "RWA basket", weight: 0.4, source: "signal_engine" },
      ],
    },
  ],
  watchlist: [
    {
      symbol: "GENIUS",
      name: "Genius",
      price: 0.496,
      change24h: 561.7,
      volume24h: 76427894,
      fdv: 496011988,
      nextUnlock: "TBD",
      nextUnlockPct: 0,
      dominantSignal: "Alpha momentum",
      confidence: 0.91,
    },
    {
      symbol: "CRMon",
      name: "Salesforce (Ondo)",
      price: 173.44,
      change24h: 5.1,
      volume24h: 50416,
      fdv: 864728,
      nextUnlock: "N/A",
      nextUnlockPct: 0,
      dominantSignal: "RWA rotation",
      confidence: 0.7,
    },
    {
      symbol: "APPon",
      name: "AppLovin (Ondo)",
      price: 419.63,
      change24h: 9.2,
      volume24h: 8980,
      fdv: 221473,
      nextUnlock: "N/A",
      nextUnlockPct: 0,
      dominantSignal: "Relative strength",
      confidence: 0.64,
    },
    {
      symbol: "BILIon",
      name: "Bilibili (Ondo)",
      price: 24.1,
      change24h: 2,
      volume24h: 15225,
      fdv: 303204,
      nextUnlock: "N/A",
      nextUnlockPct: 0,
      dominantSignal: "Theme comparison",
      confidence: 0.58,
    },
  ],
  alphaFeed: alphaTokens,
};

export const analysisWorkspaceMockData: AnalysisWorkspaceViewModel = {
  templates: [
    {
      id: "unlock_analysis",
      name: "Unlock Analysis",
      description: "对未来 30 天解锁计划、历史解锁影响和当前衍生品状态做统一研判。",
      outputFormat: "report",
      requiredData: ["unlock", "ohlcv", "oi_funding", "depth"],
      steps: [
        "查询未来 30 天解锁",
        "回看历史解锁前后 7 天价格",
        "比对当前 OI、深度、资金费率",
        "输出解锁压力判断",
      ],
    },
    {
      id: "event_analysis",
      name: "Event Analysis",
      description: "评估活动奖励发放、空投和 launchpool 造成的潜在抛压。",
      outputFormat: "report",
      requiredData: ["announcements", "circulating_supply", "ohlcv"],
      steps: [
        "统计活动分配占比",
        "估算抛压规模",
        "回测历史类似活动",
        "输出时间窗口",
      ],
    },
    {
      id: "oi_analysis",
      name: "OI Diagnostic",
      description: "联动 OI、资金费率、深度和价格判断建仓方向。",
      outputFormat: "chart_data",
      requiredData: ["oi_funding", "depth", "ohlcv"],
      steps: [
        "抓取 24h OI 曲线",
        "关联资金费率和价格",
        "对比深度变化",
        "判断多头 / 空头 / 做市调整",
      ],
    },
    {
      id: "full_checkup",
      name: "Full Checkup",
      description: "输出代币综合体检报告，适合给 AI 进一步推理。",
      outputFormat: "report",
      requiredData: ["overview", "ohlcv", "depth", "oi_funding", "unlock", "announcements", "onchain"],
      steps: [
        "基础面与流动性",
        "衍生品与深度状态",
        "事件与解锁窗口",
        "链上异常与综合评分",
      ],
    },
  ],
  selectedRun: {
    templateId: "unlock_analysis",
    symbol: "GENIUS",
    verdict: "以 GENIUS 这种 Binance Alpha 新标的做模板分析时，现阶段更应该把重点放在节奏识别和风险边界，而不是勉强补齐不存在的解锁/OI 数据。",
    confidence: 0.74,
    riskLevel: "moderate",
    keyFindings: [
      "Binance Alpha 刚上线不到 24 小时，价格和成交量都处于高波动状态。",
      "更适合先跑 momentum / liquidity 模板，再逐步补充解锁和链上数据。",
      "关注名单里最好保留同批次 RWA 标的用于横向比较。",
      "模板层需要明确缺失数据时的降级策略，避免输出伪精确分析。",
    ],
    chartSeries: [
      { label: "Momentum", value: 92 },
      { label: "Liquidity", value: 71 },
      { label: "Theme Fit", value: 66 },
      { label: "Data Completeness", value: 38 },
    ],
  },
  recentRuns: [
    { id: "run-1", templateName: "Unlock Analysis", symbol: "GENIUS", runAt: "11:05", status: "completed" },
    { id: "run-2", templateName: "OI Diagnostic", symbol: "CRMon", runAt: "10:18", status: "completed" },
    { id: "run-3", templateName: "Full Checkup", symbol: "APPon", runAt: "09:50", status: "running" },
  ],
  conversation: [
    {
      id: "msg-1",
      role: "assistant",
      content:
        "我已经把模板切到 Binance Alpha 的最近标的上。当前更适合先看 GENIUS 的波动结构，而不是直接套旧的解锁逻辑。",
      timestamp: "10:58",
    },
    {
      id: "msg-2",
      role: "user",
      content: "如果我只想跟踪 Binance Alpha 里最近最值得盯的 3 个，应该怎么排优先级？",
      timestamp: "11:01",
    },
    {
      id: "msg-3",
      role: "tool",
      content: "run_analysis_template(template_id=unlock_analysis, symbol=GENIUS)",
      timestamp: "11:02",
    },
    {
      id: "msg-4",
      role: "assistant",
      content:
        "先盯 GENIUS 看波动衰减，再用 CRMon 和 APPon 做主题对比。这样能把“高波动样本”和“稳态对照组”放在同一个观察框架里。",
      timestamp: "11:04",
    },
  ],
  tools: [
    { name: "query_token_data", description: "查询单币种多维数据，支持 exchange 和 timerange 参数。" },
    { name: "run_analysis_template", description: "执行预设模板，输出结构化报告或图表数据。" },
    { name: "compare_patterns", description: "把当前状态和历史 pre_unlock / accumulation 模式做比对。" },
    { name: "generate_trade_suggestion", description: "根据分析摘要输出方向、止损、目标位和仓位建议。" },
  ],
};

export const marketWorkspaceMockData: MarketWorkspaceViewModel = {
  focusList: dashboardMockData.watchlist,
  recentAlphaTokens: alphaTokens,
  announcements: [
    {
      id: "ann-1",
      title: "GENIUS enters Binance Alpha with rapid liquidity discovery",
      source: "Binance Alpha",
      token: "GENIUS",
      type: "Listing",
      publishTime: "2026-04-13 23:30 CST",
      summary: "上线后 24 小时成交额迅速放大，适合作为高波动跟踪样本。",
    },
    {
      id: "ann-2",
      title: "Ondo RWA basket expands on Binance Alpha",
      source: "Binance Alpha",
      token: "CRMon / COSTon / APPon",
      type: "Theme batch",
      publishTime: "2026-04-13 18:20 CST",
      summary: "同批次集中加入多个 Ondo 风格映射资产，适合做主题联动观察。",
    },
    {
      id: "ann-3",
      title: "Market desk note: compare RWA rotation with meme momentum",
      source: "Internal note",
      token: "GENIUS / APPon / BILIon",
      type: "Research",
      publishTime: "2026-04-14 09:40 CST",
      summary: "把极端动量和低换手主题标的拆开看，避免一个逻辑套所有币。",
    },
  ],
};

export const freeChatWorkspaceMockData: FreeChatWorkspaceViewModel = {
  suggestedPrompts: [
    "帮我比较 GENIUS 和 CRMon 的观察优先级",
    "如果只做 Binance Alpha 最近一批，哪些更适合放关注名单",
    "把 Ondo 这一批 RWA 标的整理成一个跟踪框架",
  ],
  conversation: [
    {
      id: "chat-1",
      role: "assistant",
      content: "自由对话区适合做探索式问题，不强制先选模板。你可以先丢一个模糊问题，我再帮你决定要不要转成模板分析。",
      timestamp: "11:08",
    },
    {
      id: "chat-2",
      role: "user",
      content: "我想知道 Binance Alpha 最近这一批里，哪些只是看热闹，哪些值得长期盯。",
      timestamp: "11:09",
    },
    {
      id: "chat-3",
      role: "assistant",
      content: "我会先把它们拆成三组: 极端动量、主题观察、对照组。这样后面无论是接模板还是接实盘跟踪都更稳。",
      timestamp: "11:10",
    },
  ],
  tools: analysisWorkspaceMockData.tools,
};
